### ISSUE TITLE
Paid sponsorship to maintain some security/privacy CLI related repos?

### ISSUE THREAD

**Issue by ChristopherA** [marlonrichert/marlonrichert#2]
I've been investigating a number of zsh cli/dotfiles projects, and found two our yours had a nice balance between being easy to begin, and yet a solid base for learning best practices.

Are you interested in monthly Github sponsorship (or be paid via bitcoin) to refactor & maintain some security & privacy related open source `zsh` and CLI libraries, with a particular emphasis on supporting them on macOS (first) and Debian (second), and be able to respond to some my design/architecture/best-practices questions, and accept some requests and features from me?

We are a not-for-profit benefit organization "Creating Open & Interoperable, Secure & Compassionate Digital Infrastructure", and our budget is not large, but we can afford an ongoing monthly budget. https://www.BlockchainCommons.com

I'm started some potential improvements to "Secure Development Setup - macOS" (currently at) https://github.com/BlockchainCommons/Secure-Development-Setup-macOS) that I've been playing around with in my gists (for instance https://gist.github.com/ChristopherA/5740eb90e2875832d9c707b49b3b89a7), and some ideas about forking it in two different sub-projects, one focused on developers wanting to do better pseudonymous development, the other moving in the other way to allow non-coders to participate in Blockchain Commons open development via git to do use cases, UX, etc. I also have some older repos I've shared in my personal Github (https://github.com/ChristopherA) including  .dotfiles approaches that feel now crufty and old fashioned.

However, in running this organization and supporting our causes, I've not been able to give them the time they deserve. I'm also seeking in these repos to move toward better shell templates and best practices, and simple testing. We do virtual internships every year, so I'm also interested in sharing best practices with them.

I don't know if you also have an interest in the blockchain world (not seeing anything obvious in your Twitter history), but we also are seeking to forward with our https://github.com/BlockchainCommons/Bitcoin-Standup-Scripts which largely use Debian scripts. But even if you are not interested in those, we have a number of privacy and security-related projects at the CLI level that don't involve cryptocurrency.

I'm open to starting with something small if you prefer. 

If you are interested in talking further, contact me at @Christopher on Twitter or [ChristopherA@LifeWithAlacrity.com](mailto:ChristopherA@LifeWithAlacrity.com).

**Comment by marlonrichert** [comment]
I sent you a DM on Twitter.
